In [ ]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8486a28a-0291-467b-bcf5-c144b32207f2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+---------+-------+----------+---------+\n",
      "| Name    |   Age |   Height |   Score |\n",
      "+=========+=======+==========+=========+\n",
      "| Evelyn  |    17 |      5.5 |      80 |\n",
      "+---------+-------+----------+---------+\n",
      "| Jessica |    16 |      6   |      85 |\n",
      "+---------+-------+----------+---------+\n",
      "| Somto   |    17 |      5.4 |      70 |\n",
      "+---------+-------+----------+---------+\n",
      "| Edith   |    18 |      5.9 |      60 |\n",
      "+---------+-------+----------+---------+\n",
      "| Liza    |    16 |      5.6 |      76 |\n",
      "+---------+-------+----------+---------+\n",
      "| Madonna |    18 |      5.5 |      66 |\n",
      "+---------+-------+----------+---------+\n",
      "| Waje    |    17 |      6   |      87 |\n",
      "+---------+-------+----------+---------+\n",
      "| Tola    |    20 |      5.7 |      95 |\n",
      "+---------+-------+----------+---------+\n",
      "| Aisha   |    19 |      5.5 |      50 |\n",
      "+---------+-------+----------+---------+\n",
      "| Latifa  |    17 |      5.5 |      49 |\n",
      "+---------+-------+----------+---------+\n",
      "| Chinedu |    19 |      5.7 |      74 |\n",
      "+---------+-------+----------+---------+\n",
      "| Liam    |    16 |      5.9 |      87 |\n",
      "+---------+-------+----------+---------+\n",
      "| Wale    |    18 |      5.8 |      75 |\n",
      "+---------+-------+----------+---------+\n",
      "| Gbenga  |    17 |      6.1 |      68 |\n",
      "+---------+-------+----------+---------+\n",
      "| Abiola  |    20 |      5.9 |      66 |\n",
      "+---------+-------+----------+---------+\n",
      "| Kola    |    19 |      5.5 |      78 |\n",
      "+---------+-------+----------+---------+\n",
      "| Kunle   |    16 |      5.6 |      87 |\n",
      "+---------+-------+----------+---------+\n",
      "| George  |    18 |      5.4 |      98 |\n",
      "+---------+-------+----------+---------+\n",
      "| Thomas  |    17 |      5.8 |      54 |\n",
      "+---------+-------+----------+---------+\n",
      "| Wesley  |    19 |      5.7
   "source": [
    "from tabulate import tabulate\n",
    "\n",
    "# Data\n",
    "students = [\n",
    "    [\"Evelyn\", 17, 5.5, 80], [\"Jessica\", 16, 6.0, 85], [\"Somto\", 17, 5.4, 70], [\"Edith\", 18, 5.9, 60],\n",
    "    [\"Liza\", 16, 5.6, 76], [\"Madonna\", 18, 5.5, 66], [\"Waje\", 17, 6.0, 87], [\"Tola\", 20, 5.7, 95],\n",
    "    [\"Aisha\", 19, 5.5, 50], [\"Latifa\", 17, 5.5, 49], \n",
    "    \n",
    "    [\"Chinedu\", 19, 5.7, 74], [\"Liam\", 16, 5.9, 87], [\"Wale\", 18, 5.8, 75], [\"Gbenga\", 17, 6.1, 68],\n",
    "    [\"Abiola\", 20, 5.9, 66], [\"Kola\", 19, 5.5, 78], [\"Kunle\", 16, 5.6, 87], [\"George\", 18, 5.4, 98],\n",
    "    [\"Thomas\", 17, 5.8, 54], [\"Wesley\", 19, 5.7, 60]\n",
    "]\n",
    "\n",
    "# Display table\n",
    "headers = [\"Name\", \"Age\", \"Height\", \"Score\"]\n",
    "print(tabulate(students, headers=headers, tablefmt=\"grid\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "714513bd-f12a-4657-8c0a-9386341cfdc1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}